#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jetty-parent
Version  : 8
Release  : 1
URL      : https://github.com/eclipse/jetty.parent/archive/jetty-parent-8.tar.gz
Source0  : https://github.com/eclipse/jetty.parent/archive/jetty-parent-8.tar.gz
Source1  : https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-parent/14/jetty-parent-14.pom
Source2  : https://repo1.maven.org/maven2/org/mortbay/jetty/jetty-parent/10/jetty-parent-10.pom
Source3  : https://repo1.maven.org/maven2/org/mortbay/jetty/jetty-parent/7/jetty-parent-7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 EPL-1.0
Requires: mvn-jetty-parent-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jetty-parent package.
Group: Data

%description data
data components for the mvn-jetty-parent package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/eclipse/jetty/jetty-parent/14
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/eclipse/jetty/jetty-parent/14

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mortbay/jetty/jetty-parent/10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/mortbay/jetty/jetty-parent/10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mortbay/jetty/jetty-parent/7
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/mortbay/jetty/jetty-parent/7


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/eclipse/jetty/jetty-parent/14/jetty-parent-14.pom
/usr/share/java/.m2/repository/org/mortbay/jetty/jetty-parent/10/jetty-parent-10.pom
/usr/share/java/.m2/repository/org/mortbay/jetty/jetty-parent/7/jetty-parent-7.pom
